version: "3.8"

x-proxy_settings: &proxy_settings
    http_proxy: &http_proxy "${HTTP_PROXY_FOR_PROXY:?HTTP_PROXY_FOR_PROXY must be set. Prease read README}"
    https_proxy: *http_proxy
    HTTP_PROXY: *http_proxy
    HTTPS_PROXY: *http_proxy

services:
    proxy:
        build:
            context: .
            args:
                <<: *proxy_settings
        environment:
            <<: *proxy_settings
        ports:
            - "${HOST_PORT:-8080}:8080"
